packages:
    asm89/stack-cors: v2.4.0
    chi-teck/drupal-code-generator: 4.2.0
    composer/installers: v2.3.0
    composer/semver: 3.4.4
    consolidation/annotated-command: 4.10.5
    consolidation/config: 3.2.1
    consolidation/filter-via-dot-access-data: 2.0.3
    consolidation/log: 3.1.2
    consolidation/output-formatters: 4.7.1
    consolidation/robo: 5.1.1
    consolidation/site-alias: 4.1.3
    consolidation/site-process: 6.1.0
    cweagans/composer-configurable-plugin: 2.0.0
    cweagans/composer-patches: 2.0.0
    defuse/php-encryption: v2.4.0
    dflydev/dot-access-data: v3.0.3
    doctrine/lexer: 3.0.1
    drupal/ai: 1.4.8
    drupal/ai_agents: 1.3.5
    drupal/ai_provider_openai: 1.3.0-beta2
    drupal/canvas: 1.10.1
    drupal/consumers: 1.24.0
    drupal/core: 11.4.6
    drupal/core-composer-scaffold: 11.4.6
    drupal/core-project-message: 11.4.6
    drupal/core-recipe-unpack: 11.4.6
    drupal/core-recommended: 11.4.6
    drupal/ctools: 4.1.1
    drupal/key: 1.22.0
    drupal/modeler_api: 1.1.5
    drupal/pathauto: 1.15.0
    drupal/simple_oauth: 6.1.1
    drupal/token: 1.17.0
    drush/drush: 13.7.6
    egulias/email-validator: 4.0.4
    grasmash/expander: 3.0.1
    grasmash/yaml-cli: 3.2.1
    guzzlehttp/guzzle: 7.15.5
    guzzlehttp/promises: 2.5.3
    guzzlehttp/psr7: 2.13.1
    joachim-n/composer-manifest: 1.1.7
    justinrainbow/json-schema: 6.8.2
    laravel/prompts: v0.3.24
    lcobucci/jwt: 5.6.0
    league/container: 4.2.5
    league/event: 3.0.3
    league/html-to-markdown: 5.1.1
    league/oauth2-server: 9.4.1
    league/uri: 7.8.1
    league/uri-interfaces: 7.8.1
    marc-mabe/php-enum: v4.7.2
    masterminds/html5: 2.10.1
    mck89/peast: v1.17.7
    nikic/php-parser: v5.8.0
    openai-php/client: v0.20.1
    paragonie/random_compat: v9.99.100
    pear/archive_tar: 1.6.1
    pear/console_getopt: v1.4.3
    pear/pear-core-minimal: v1.10.18
    pear/pear_exception: v1.0.2
    phootwork/collection: v3.2.3
    phootwork/lang: v3.2.3
    php-http/discovery: 1.20.0
    php-http/multipart-stream-builder: 1.4.2
    php-tuf/composer-stager: v2.1.1
    phpowermove/docblock: v4.0
    psr/clock: 1.0.0
    psr/container: 2.0.2
    psr/event-dispatcher: 1.0.0
    psr/http-client: 1.0.3
    psr/http-factory: 1.1.0
    psr/http-message: '2.0'
    psr/http-server-handler: 1.0.2
    psr/http-server-middleware: 1.0.2
    psr/log: 3.0.2
    psy/psysh: v0.12.24
    ralouphie/getallheaders: 3.0.3
    revolt/event-loop: v1.0.9
    sebastian/diff: 7.0.1
    steverhoades/oauth2-openid-connect-server: v3.0.1
    symfony/console: v7.4.18
    symfony/dependency-injection: v7.4.17
    symfony/deprecation-contracts: v3.7.1
    symfony/error-handler: v7.4.17
    symfony/event-dispatcher: v7.4.17
    symfony/event-dispatcher-contracts: v3.7.1
    symfony/filesystem: v7.4.18
    symfony/finder: v7.4.17
    symfony/http-foundation: v7.4.18
    symfony/http-kernel: v7.4.18
    symfony/mailer: v7.4.17
    symfony/mime: v7.4.18
    symfony/polyfill-ctype: v1.37.0
    symfony/polyfill-iconv: v1.37.0
    symfony/polyfill-intl-grapheme: v1.41.0
    symfony/polyfill-intl-idn: v1.42.0
    symfony/polyfill-intl-normalizer: v1.42.0
    symfony/polyfill-mbstring: v1.38.2
    symfony/polyfill-php80: v1.37.0
    symfony/polyfill-php81: v1.38.1
    symfony/polyfill-php83: v1.41.0
    symfony/polyfill-php84: v1.38.1
    symfony/polyfill-php85: v1.41.0
    symfony/polyfill-php86: v1.41.0
    symfony/process: v7.4.18
    symfony/psr-http-message-bridge: v7.4.8
    symfony/routing: v7.4.18
    symfony/runtime: v7.4.14
    symfony/serializer: v7.4.18
    symfony/service-contracts: v3.7.3
    symfony/string: v7.4.15
    symfony/translation-contracts: v3.7.1
    symfony/validator: v7.4.18
    symfony/var-dumper: v7.4.18
    symfony/var-exporter: v7.4.18
    symfony/yaml: v7.4.18
    twig/html-extra: v3.28.0
    twig/twig: v3.28.0
    yethee/tiktoken: 0.5.1
