#!/usr/bin/env bash

## Description: Pull page/content-template/region edits made in the Drupal UI back into canvas_components/
## Usage: pull-components
## Example: "ddev pull-components"

set -e

cd "$DDEV_APPROOT"
source ./canvas-common.sh

ensure_canvas_env "$DDEV_PRIMARY_URL"
canvas_run pull
