#!/usr/bin/env bash

## Description: Push Canvas component/page/content-template/region changes to this project's Drupal site
## Usage: push-components
## Example: "ddev push-components"

set -e

cd "$DDEV_APPROOT"
source ./canvas-common.sh

ensure_canvas_env "$DDEV_PRIMARY_URL"
canvas_run push
